import { getStudyTopics } from './departmentSkills';
import { calculateReadiness, generateSkillScores, getCompanyRequirements, calculateSkillGaps } from './scoreCalculator';

const getCompanyData = (targetCompany) => {
  const companyData = {
    "Amazon": {
      overview: "Amazon seeks candidates with strong problem-solving skills, system design knowledge, and leadership principles alignment.",
      requirements: ["Data Structures & Algorithms", "System Design", "Behavioral (Leadership Principles)", "Coding Proficiency"],
      interviewPattern: "2 Online Assessments → Phone Screen → 4-5 Onsite Rounds (Coding + System Design + Behavioral)"
    },
    "Google": {
      overview: "Google emphasizes algorithmic thinking, scalability, and innovation. Candidates must excel in coding and system design.",
      requirements: ["Advanced Algorithms", "Distributed Systems", "Code Optimization", "Product Sense"],
      interviewPattern: "Phone Screen → 4-5 Technical Rounds (Algorithms + System Design + Googleyness)"
    },
    "Microsoft": {
      overview: "Microsoft values technical depth, collaboration, and growth mindset. Strong coding and design skills required.",
      requirements: ["Data Structures", "Object-Oriented Design", "Cloud Technologies", "Problem Solving"],
      interviewPattern: "Phone Screen → Onsite (Coding + Design + Behavioral)"
    },
    "Infosys": {
      overview: "Infosys focuses on foundational programming, aptitude, and communication skills for entry-level roles.",
      requirements: ["Programming Basics", "Aptitude", "Communication", "Domain Knowledge"],
      interviewPattern: "Online Test → Technical Interview → HR Round"
    },
    "TCS": {
      overview: "TCS evaluates candidates on programming fundamentals, logical reasoning, and communication.",
      requirements: ["C/Java/Python", "Aptitude & Reasoning", "Communication", "Basic CS Concepts"],
      interviewPattern: "National Qualifier Test → Technical + HR Interview"
    },
    "Wipro": {
      overview: "Wipro assesses coding ability, problem-solving, and communication for campus placements.",
      requirements: ["Programming", "Logical Reasoning", "Verbal Ability", "Technical Knowledge"],
      interviewPattern: "Online Test → Technical Interview → HR Round"
    },
    "Startup": {
      overview: "Startups seek versatile engineers with hands-on experience, quick learning ability, and ownership mindset.",
      requirements: ["Full-Stack Skills", "Problem Solving", "Real Projects", "Adaptability"],
      interviewPattern: "Take-home Assignment → Technical Discussion → Culture Fit"
    }
  };
  return companyData[targetCompany] || companyData["Startup"];
};

const generateExplanation = (scores, formData, skillGaps) => {
  const weakSkills = skillGaps.filter(s => s.gap > 10).map(s => s.name).slice(0, 3).join(", ");
  const departmentText = formData.department;

  if (scores.gap > 20) {
    return `This readiness score is generated by analyzing the candidate's skills in ${departmentText} and comparing them with industry hiring requirements for ${departmentText.toLowerCase()} roles. Significant preparation needed. Focus on ${weakSkills || "core fundamentals"}. Your current readiness is ${scores.current}% but ${formData.targetCompany} expects ${scores.target}%.`;
  } else if (scores.gap > 10) {
    return `This readiness score is generated by analyzing the candidate's skills in ${departmentText} and comparing them with industry hiring requirements for ${departmentText.toLowerCase()} roles. You're on the right track but need focused improvement in ${weakSkills || "key areas"}. Bridge the ${scores.gap}% gap with consistent practice.`;
  } else {
    return `This readiness score is generated by analyzing the candidate's skills in ${departmentText} and comparing them with industry hiring requirements for ${departmentText.toLowerCase()} roles. Strong profile! You're ${scores.current}% ready. Fine-tune your skills and you'll be competitive for ${formData.targetCompany}.`;
  }
};

const generateRoadmap = (formData, skillGaps) => {
  const months = Number(formData.monthsAvailable);
  const department = formData.department;
  const topWeakSkills = skillGaps.sort((a, b) => b.gap - a.gap).slice(0, 3).map(s => s.name);

  if (department === "Computer Science" || department === "Information Technology") {
    if (months <= 3) {
      return [
        { phase: "Month 1", focus: "DSA Fundamentals", tasks: ["Arrays, Strings, Linked Lists", "Basic sorting & searching", "Solve 50 easy problems"] },
        { phase: "Month 2", focus: "Advanced DSA", tasks: ["Trees, Graphs, DP", "Solve 40 medium problems", "Mock interviews"] },
        { phase: "Month 3", focus: "System Design & Projects", tasks: ["Design patterns", "Build 1 full-stack project", "Final preparation"] }
      ];
    } else if (months <= 6) {
      return [
        { phase: "Month 1-2", focus: "DSA Foundation", tasks: ["Master all data structures", "100 LeetCode problems", "Time complexity analysis"] },
        { phase: "Month 3-4", focus: "Advanced Problem Solving", tasks: ["Dynamic Programming", "Graph algorithms", "System design basics"] },
        { phase: "Month 5-6", focus: "Interview Prep", tasks: ["Mock interviews", "Build 2 projects", "Company-specific preparation"] }
      ];
    } else {
      return [
        { phase: "Month 1-3", focus: "Strong Foundation", tasks: ["Complete DSA course", "150 problems", "CS fundamentals"] },
        { phase: "Month 4-6", focus: "Intermediate Skills", tasks: ["Advanced algorithms", "System design", "Open source contributions"] },
        { phase: "Month 7+", focus: "Expert Level", tasks: ["Competitive programming", "Multiple projects", "Interview mastery"] }
      ];
    }
  }

  if (department === "Mechanical") {
    if (months <= 3) {
      return [
        { phase: "Month 1", focus: topWeakSkills[0] || "Core Mechanics", tasks: ["Review fundamental concepts", "Practice numerical problems", "Study industry applications"] },
        { phase: "Month 2", focus: topWeakSkills[1] || "CAD & Design", tasks: ["Master CAD software", "Complete 5 design projects", "Learn manufacturing processes"] },
        { phase: "Month 3", focus: "Interview Preparation", tasks: ["Technical interview prep", "Domain knowledge review", "Mock interviews"] }
      ];
    } else if (months <= 6) {
      return [
        { phase: "Month 1-2", focus: "Engineering Fundamentals", tasks: ["Thermodynamics mastery", "Mechanics problem solving", "Material science concepts"] },
        { phase: "Month 3-4", focus: "Design & Manufacturing", tasks: ["Advanced CAD modeling", "Manufacturing process optimization", "Quality control methods"] },
        { phase: "Month 5-6", focus: "Industry Readiness", tasks: ["Real-world projects", "Industry certifications", "Interview preparation"] }
      ];
    } else {
      return [
        { phase: "Month 1-3", focus: "Core Engineering", tasks: ["Master all core subjects", "Solve 100+ numerical problems", "Build strong foundation"] },
        { phase: "Month 4-6", focus: "Specialized Skills", tasks: ["Advanced CAD/CAM", "Thermal analysis", "Design optimization"] },
        { phase: "Month 7+", focus: "Professional Development", tasks: ["Industry projects", "Certifications (AutoCAD, SolidWorks)", "Interview mastery"] }
      ];
    }
  }

  if (department === "Civil") {
    if (months <= 3) {
      return [
        { phase: "Month 1", focus: topWeakSkills[0] || "Structural Basics", tasks: ["Structural analysis fundamentals", "Load calculations", "Design principles"] },
        { phase: "Month 2", focus: topWeakSkills[1] || "Design Tools", tasks: ["AutoCAD proficiency", "Surveying techniques", "Construction planning"] },
        { phase: "Month 3", focus: "Interview Preparation", tasks: ["Technical concepts review", "Project discussions", "Mock interviews"] }
      ];
    } else if (months <= 6) {
      return [
        { phase: "Month 1-2", focus: "Core Civil Engineering", tasks: ["Structural engineering", "Surveying mastery", "Building codes & standards"] },
        { phase: "Month 3-4", focus: "Design & Management", tasks: ["AutoCAD projects", "Construction management", "Project estimation"] },
        { phase: "Month 5-6", focus: "Professional Skills", tasks: ["Real construction projects", "Site management", "Interview preparation"] }
      ];
    } else {
      return [
        { phase: "Month 1-3", focus: "Engineering Foundation", tasks: ["Master structural analysis", "Complete surveying course", "Design fundamentals"] },
        { phase: "Month 4-6", focus: "Advanced Topics", tasks: ["Geotechnical engineering", "Advanced AutoCAD", "Environmental engineering"] },
        { phase: "Month 7+", focus: "Industry Expertise", tasks: ["Multiple design projects", "Construction site experience", "Professional certifications"] }
      ];
    }
  }

  if (department === "Electronics") {
    if (months <= 3) {
      return [
        { phase: "Month 1", focus: "Circuit Fundamentals", tasks: ["Digital electronics", "Circuit analysis", "Basic microcontrollers"] },
        { phase: "Month 2", focus: "Embedded Systems", tasks: ["Microcontroller programming", "Communication protocols", "PCB basics"] },
        { phase: "Month 3", focus: "Projects & Interview Prep", tasks: ["Build 2 embedded projects", "Signal processing review", "Technical interviews"] }
      ];
    } else if (months <= 6) {
      return [
        { phase: "Month 1-2", focus: "Core Electronics", tasks: ["Circuit design mastery", "Signal processing", "Communication systems"] },
        { phase: "Month 3-4", focus: "Embedded & Programming", tasks: ["Advanced microcontrollers", "Embedded C/C++", "RTOS concepts"] },
        { phase: "Month 5-6", focus: "Industry Projects", tasks: ["IoT projects", "PCB design", "Interview preparation"] }
      ];
    } else {
      return [
        { phase: "Month 1-3", focus: "Strong Foundation", tasks: ["Master all core subjects", "Circuit simulation", "Programming skills"] },
        { phase: "Month 4-6", focus: "Specialized Skills", tasks: ["VLSI design", "Advanced embedded systems", "IoT development"] },
        { phase: "Month 7+", focus: "Professional Level", tasks: ["Multiple projects", "Industry certifications", "Open source contributions"] }
      ];
    }
  }

  if (months <= 3) {
    return [
      { phase: "Month 1", focus: "Core Concepts", tasks: ["Review fundamental concepts", "Practice problems", "Build foundation"] },
      { phase: "Month 2", focus: "Advanced Topics", tasks: ["Specialized skills", "Practical applications", "Project work"] },
      { phase: "Month 3", focus: "Interview Ready", tasks: ["Mock interviews", "Final review", "Company preparation"] }
    ];
  } else if (months <= 6) {
    return [
      { phase: "Month 1-2", focus: "Foundation Building", tasks: ["Master core subjects", "Problem solving", "Technical skills"] },
      { phase: "Month 3-4", focus: "Skill Development", tasks: ["Advanced topics", "Practical projects", "Domain expertise"] },
      { phase: "Month 5-6", focus: "Interview Preparation", tasks: ["Mock interviews", "Company research", "Final preparation"] }
    ];
  } else {
    return [
      { phase: "Month 1-3", focus: "Strong Foundation", tasks: ["Complete core curriculum", "Build fundamental skills", "Practice regularly"] },
      { phase: "Month 4-6", focus: "Advanced Skills", tasks: ["Specialized knowledge", "Multiple projects", "Industry exposure"] },
      { phase: "Month 7+", focus: "Expert Level", tasks: ["Professional projects", "Certifications", "Interview mastery"] }
    ];
  }
};

export const generateAIAnalysis = (formData) => {
  const scores = calculateReadiness(formData, formData.department);
  const candidateSkills = generateSkillScores(formData.department, scores.current);
  const companyRequirements = getCompanyRequirements(formData.targetCompany, formData.department);
  const skillGaps = calculateSkillGaps(candidateSkills, companyRequirements);
  
  return {
    scores,
    company: getCompanyData(formData.targetCompany),
    candidateSkills,
    companyRequirements,
    skillGaps,
    aiExplanation: generateExplanation(scores, formData, skillGaps),
    roadmap: generateRoadmap(formData, skillGaps),
    studyTopics: getStudyTopics(formData.department)
  };
};
